apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: Creates a EKS cluster with JupyterHub + extra enabled through Terraform
  name: jupyterhub-on-eks
  title: Create Data on EKS - JupyterHub
spec:
  owner: guest
  type: service
  parameters:
    - title: Terraform config options
      properties:
        tfVars:
          properties:
            acm_certificate_domain:
              default: ""
              description: Enter domain name with wildcard and ensure ACM certificate is created for this domain name, e.g. *.example.com
              type: string
            cognito_custom_domain:
              default: eks
              description: Cognito domain prefix for Hosted UI authentication endpoints
              type: string
            eks_cluster_version:
              default: "1.27"
              description: EKS Cluster version
              type: string
            jupyter_hub_auth_mechanism:
              default: dummy
              description: 'Allowed values: cognito, dummy'
              type: string
            jupyterhub_domain:
              default: ""
              description: Enter sub-domain name for jupyterhub to be hosted,  e.g. eks.example.com. Only needed if auth mechanism is set to cognito
              type: string
            name:
              default: jupyterhub-on-eks
              description: Name of the VPC and EKS Cluster
              type: string
            region:
              default: us-west-2
              description: Region
              type: string
            secondary_cidr_blocks:
              default:
                - 100.64.0.0/16
              description: Secondary CIDR blocks to be attached to VPC
              items:
                type: string
              type: array
            vpc_cidr:
              default: 10.1.0.0/21
              description: VPC CIDR. This should be a valid private (RFC 1918) CIDR range
              type: string
          title: Terraform variables
          type: object
    - title: Configuration Options
      properties:
        adminRoleName:
          default: Admin
          description: Name of the role to give the administrative rights on the EKS cluster.
          title: Admin Role Name
          type: string
        clusterName:
          description: The cluster to run this workflow in.
          title: Cluster to run
          type: string
          ui:field: KubernetesClusterPicker
        name:
          title: name of this entry
          type: string
        namespace:
          default: data-on-eks
          title: namespace within the kubernetes cluster to deploy this
          type: string
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: create-repo
      name: Create Repository
      action: github:repo:create
      input:
        repoUrl: ${{ parameters.repoUrl }}
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./templates-jupyterhub/
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          tfVars: ${{ parameters.tfVars }}
          adminRoleName: ${{parameters.adminRoleName}}
          clusterName: ${{ parameters.clusterName }}
    - id: init-repo
      name: Initialize Repository
      action: github:repo:push
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
    - id: wait
      name: Waiting for the repo to be ready
      action: "roadiehq:utils:sleep"
      input:
        amount: 5
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['init-repo'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
    - id: apply-cm
      name: Apply TF variables CM
      action: cnoe:kubernetes:apply
      input:
        manifestPath: cm.yaml
        namespaced: true
        clusterName: ${{ parameters.clusterName }}
    - id: apply-workflow
      name: Start TF workflow
      action: cnoe:kubernetes:apply
      input:
        manifestPath: workflow.yaml
        namespaced: true
        clusterName: ${{ parameters.clusterName }}
  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
