apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: infra-monitoring-
  namespace: ${{values.namespace}}
  labels:
    backstage-id: eks-cluster-${{values.name}}
    env: dev
spec:
  arguments:
    parameters:
      - name: backstage-entity-name
        value: eks-cluster-${{values.name}}
      - name: script-location
        value: examples/existing-cluster-with-base-and-infra
      - name: admin-role
        value: ${{values.adminRoleName}}
  workflowTemplateRef:
    name: terraform-eks-observability
    clusterScope: true
